env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-C opt-level=2 -C codegen-units=8"
    - PATH=$PATH:$HOME/.cargo/bin
    - TEST=foo
language: rust
rust:
  - 1.29.1
stages:
  - build
  - tests
  - deploy
cache:
  cargo: true
jobs:
  include:
    - stage: build
      name: "build real"
      script:
        - mkdir artifacts
        - TEST=bar
      os: linux

    - stage: tests
      name: "mock tests"
      script:
        - echo $TEST
      os: linux

    - stage: deploy
      name: "package and deploy artifacts"
      script:
        - echo $TEST
      os: linux
