env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-C opt-level=2 -C codegen-units=8"
    - PATH=$PATH:$HOME/.cargo/bin
language: rust
rust:
  - 1.29.1
stages:
  - build
jobs:
  include:
    - stage: build
      before_script:
        - apt-get install -y tree
        - docker pull jacderida/travis_docker_test:0.0.1
      script:
        - docker run --rm --name arithmetic_app -v "$PWD":/usr/src/adder jacderida/travis_docker_test:0.0.1 cargo test --target-dir /target
        - docker cp arithmetic_app:/target .
        - echo $UID
        - echo $USERNAME
        - id -g
        - id -u
        - tree target
      os: linux
