env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-C opt-level=2 -C codegen-units=8"
    - PATH=$PATH:$HOME/.cargo/bin
language: rust
rust:
  - 1.29.1
stages:
  - build
jobs:
  include:
    - stage: build
      before_script:
        - sudo apt-get install -y tree
        - docker pull jacderida/travis_docker_test:0.0.2
      script:
        - docker run --name arithmetic_app -v "$PWD":/usr/src/adder -u 2000:2000 jacderida/travis_docker_test:0.0.1 cargo test --target-dir /target
        - docker cp arithmetic_app:/target .
        - id
        - tree target
        - ls -al target/debug
      os: linux
